export type ItineraryStop = {
  id: string
  time: string
  name: string
  kind: 'eat' | 'do' | 'shop' | 'fiesta'
  distance: string
  area: string
  why: string
  note?: string
  href: string
  linkLabel: string
  indoor?: boolean
  closedWeekdays?: number[]
  alternate?: ItineraryStop
}

export type Itinerary = {
  id: string
  eyebrow: string
  label: string
  hook: string
  timing: string
  bestFor: string
  accent: 'terra' | 'turq' | 'sage' | 'gold'
  stops: ItineraryStop[]
}

const mapsLink = (query: string) =>
  `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`

/**
 * Distances are practical, rounded driving-mile estimates from Balloon Fiesta Park,
 * 4401 Alameda Blvd NE. ZIP/area labels make the routes scannable without promising
 * normal drive times during Fiesta traffic.
 */
export const ITINERARIES: Itinerary[] = [
  {
    id: 'left-the-field',
    eyebrow: 'After a morning session',
    label: 'Just left the field',
    hook: 'Warm up, eat something with chile, then make an easy wander of the late morning.',
    timing: '9:00am–2:00pm',
    bestFor: 'Solo travelers + couples',
    accent: 'terra',
    stops: [
      {
        id: 'balloon-museum',
        time: '9:00am',
        name: 'Anderson Abruzzo Balloon Museum',
        kind: 'do',
        distance: 'Next to the field',
        area: '87113 · Balloon Fiesta Park',
        why: 'Stay parked and put the morning in context with ballooning history, science, and great views back over the launch field.',
        note: 'Check Fiesta-week hours before walking over.',
        href: mapsLink('Anderson Abruzzo Albuquerque International Balloon Museum'),
        linkLabel: 'Open in Maps',
        indoor: true,
        closedWeekdays: [1],
        alternate: {
          id: 'los-poblanos-monday',
          time: '9:00am',
          name: 'Los Poblanos Farm Shop + bakery',
          kind: 'shop',
          distance: 'About 9 miles',
          area: '87107 · Los Ranchos',
          why: 'The Balloon Museum is closed Monday, so start with pastries, coffee, New Mexico provisions, and lavender goods at the farm shop instead.',
          note: 'Farm Shop opens daily at 8am; the bakery counter is open daily 8am–4pm.',
          href: 'https://lospoblanos.com/shop/farm-shop',
          linkLabel: 'Check shop details',
          indoor: true,
        },
      },
      {
        id: 'indian-pueblo-kitchen',
        time: '10:30am',
        name: 'Indian Pueblo Kitchen',
        kind: 'eat',
        distance: 'About 10 miles',
        area: '87104 · 12th Street',
        why: 'A real New Mexico breakfast or early lunch—blue corn, red and green chile, stews, and breads—inside a center owned by the 19 Pueblos.',
        note: 'Open daily 9am–5pm; the museum and store make this an easy two-for-one stop.',
        href: 'https://indianpueblo.org/restaurant/',
        linkLabel: 'See the kitchen',
        indoor: true,
      },
      {
        id: 'indian-pueblo-store',
        time: '11:45am',
        name: 'Indian Pueblo Store + museum',
        kind: 'shop',
        distance: 'Same stop',
        area: '87104 · 12th Street',
        why: 'Meet artists, shop Native-made jewelry and pottery, and learn whose land and traditions shape this place.',
        href: 'https://indianpueblo.org/plan-your-visit/',
        linkLabel: 'Plan the visit',
        indoor: true,
      },
      {
        id: 'old-town-plaza',
        time: '1:00pm',
        name: 'Old Town Plaza',
        kind: 'shop',
        distance: 'About 12 miles',
        area: '87104 · Old Town',
        why: 'Browse local shops, patios, galleries, and adobe lanes at your own pace before the afternoon crowds peak.',
        href: mapsLink('Old Town Plaza Albuquerque NM'),
        linkLabel: 'Open in Maps',
      },
    ],
  },
  {
    id: 'family-day',
    eyebrow: 'Hands-on + kid-easy',
    label: 'Family day',
    hook: 'Keep the wonder going without making everyone spend the afternoon in the car.',
    timing: '10:00am–6:30pm',
    bestFor: 'Families + mixed ages',
    accent: 'turq',
    stops: [
      {
        id: 'explora',
        time: '10:00am',
        name: 'Explora',
        kind: 'do',
        distance: 'About 12 miles',
        area: '87104 · Museum Row',
        why: 'More than 250 hands-on science, art, and engineering exhibits—excellent after children have already been awake since 4am.',
        note: 'Open daily 10am–5pm; Monday toddler time begins at 9am.',
        href: 'https://www.explora.us/visitor-information/',
        linkLabel: 'Hours + tickets',
        indoor: true,
      },
      {
        id: 'natural-history-museum',
        time: '12:30pm',
        name: 'New Mexico Museum of Natural History',
        kind: 'do',
        distance: 'Across the street',
        area: '87104 · Museum Row',
        why: 'Dinosaurs, space, and New Mexico geology in a manageable museum that does not require another drive.',
        href: 'https://www.nmnaturalhistory.org/visitors/visitor-information',
        linkLabel: 'Plan the museum',
        indoor: true,
        closedWeekdays: [2],
        alternate: {
          id: 'albuquerque-museum-tuesday',
          time: '12:30pm',
          name: 'Albuquerque Museum',
          kind: 'do',
          distance: 'Across from Museum Row',
          area: '87104 · Old Town',
          why: 'The Natural History Museum is closed Tuesday, so switch to Albuquerque art and history without moving the car far.',
          note: 'This Tuesday substitution keeps the family route indoors and in the same neighborhood.',
          href: 'https://www.cabq.gov/artsculture/albuquerque-museum/plan-your-visit',
          linkLabel: 'Plan the museum',
          indoor: true,
        },
      },
      {
        id: 'old-town-family',
        time: '3:00pm',
        name: 'Old Town snack + shop wander',
        kind: 'shop',
        distance: 'About 1 mile away',
        area: '87104 · Old Town',
        why: 'Let everyone choose a treat, browse small shops, and catch Fiesta-week music around the plaza without a rigid agenda.',
        href: 'https://www.cabq.gov/artsculture/historic-old-town/balloon-fiesta-week-in-old-town',
        linkLabel: 'See Fiesta-week music',
      },
      {
        id: 'sawmill-family',
        time: '5:00pm',
        name: 'Sawmill Market',
        kind: 'eat',
        distance: 'About 12 miles from field',
        area: '87104 · Sawmill District',
        why: 'A local food hall solves the family dinner standoff: New Mexican food, pizza, pasta, sweets, and room to spread out.',
        href: 'https://www.sawmillmarket.com/merchants',
        linkLabel: 'Browse food stalls',
        indoor: true,
      },
    ],
  },
  {
    id: 'foodie-day',
    eyebrow: 'Eat your way across town',
    label: 'Foodie day out',
    hook: 'One distinctly New Mexican meal, one excellent wander, and a dinner worth planning ahead for.',
    timing: '9:30am–8:30pm',
    bestFor: 'Couples + groups',
    accent: 'gold',
    stops: [
      {
        id: 'golden-crown',
        time: '9:30am',
        name: 'Golden Crown Panaderia',
        kind: 'eat',
        distance: 'About 12 miles',
        area: '87104 · Old Town edge',
        why: 'Refuel with green chile bread, pastries, coffee, and one of Albuquerque’s most lovable neighborhood bakery stops.',
        href: mapsLink('Golden Crown Panaderia Albuquerque NM'),
        linkLabel: 'Open in Maps',
        indoor: true,
      },
      {
        id: 'old-town-foodie',
        time: '11:00am',
        name: 'Old Town galleries + local shops',
        kind: 'shop',
        distance: 'About 1 mile away',
        area: '87104 · Old Town',
        why: 'Walk off breakfast among independent galleries, tucked-away courtyards, chile shops, and New Mexico-made gifts.',
        href: mapsLink('Old Town Plaza Albuquerque NM'),
        linkLabel: 'Open in Maps',
      },
      {
        id: 'los-poblanos-farm-shop',
        time: '2:00pm',
        name: 'Los Poblanos Farm Shop',
        kind: 'shop',
        distance: 'About 9 miles from field',
        area: '87107 · Los Ranchos',
        why: 'Shop lavender goods and New Mexico provisions on one of the city’s loveliest working-farm properties.',
        note: 'The farm is private beyond guest areas; follow signs and posted access rules.',
        href: 'https://lospoblanos.com/shop/farm-shop',
        linkLabel: 'Check shop hours',
      },
      {
        id: 'campo',
        time: '5:30pm',
        name: 'Campo at Los Poblanos',
        kind: 'eat',
        distance: 'Same property',
        area: '87107 · Los Ranchos',
        why: 'Finish with Rio Grande Valley cooking built around the farm’s harvest—a memorable splurge instead of another generic vacation dinner.',
        note: 'Reserve well ahead for Fiesta week.',
        href: 'https://lospoblanos.com/dining/campo-reservations',
        linkLabel: 'Plan dinner',
        indoor: true,
      },
    ],
  },
  {
    id: 'evening-glow',
    eyebrow: 'Build toward the night session',
    label: 'Chasing the evening glow',
    hook: 'See the city from above, eat near the field, then return before traffic becomes the main event.',
    timing: '10:30am–9:00pm',
    bestFor: 'First-timers + view seekers',
    accent: 'sage',
    stops: [
      {
        id: 'sandia-tram',
        time: '10:30am',
        name: 'Sandia Peak Tramway',
        kind: 'do',
        distance: 'About 13 miles',
        area: '87122 · Sandia foothills',
        why: 'Ride above the city for the enormous view that makes Albuquerque’s geography click—then come down with plenty of buffer before Fiesta traffic.',
        note: 'Book ahead. Weather can pause operations; do not make this a tight connection.',
        href: 'https://sandiapeak.com/',
        linkLabel: 'Tickets + status',
      },
      {
        id: 'tram-gift-shop',
        time: '12:30pm',
        name: 'Tram gift shop + foothills pause',
        kind: 'shop',
        distance: 'Same stop',
        area: '87122 · Sandia foothills',
        why: 'Leave room for the line down, a souvenir, and changing mountain weather instead of racing the clock.',
        href: mapsLink('Sandia Peak Tramway Albuquerque NM'),
        linkLabel: 'Open in Maps',
      },
      {
        id: 'tin-can-alley',
        time: '2:00pm',
        name: 'Tin Can Alley',
        kind: 'eat',
        distance: 'About 5 miles from field',
        area: '87113 · North I-25',
        why: 'An early, flexible food-hall stop close to the park lets groups split up for tacos, burgers, drinks, or coffee without a long detour.',
        href: mapsLink('Tin Can Alley Albuquerque NM'),
        linkLabel: 'Open in Maps',
        indoor: true,
      },
      {
        id: 'official-evening-session',
        time: 'By 3:00pm',
        name: 'Back to Balloon Fiesta Park',
        kind: 'fiesta',
        distance: '4401 Alameda Blvd NE',
        area: '87113 · Balloon Fiesta Park',
        why: 'Get back early, then use the official schedule for tonight’s named program. Special Shape Glowdeo is specifically Oct 8–9—not every evening.',
        note: 'Evening sessions run roughly 3–9pm. Live program and weather decisions belong to the official Fiesta.',
        href: 'https://www.balloonfiesta.com/plan-your-visit/event-schedule/',
        linkLabel: 'Check official schedule',
      },
    ],
  },
  {
    id: 'weather-backup',
    eyebrow: 'When the balloons stay down',
    label: 'Weather backup',
    hook: 'Ascensions get called off some mornings. Your day in Albuquerque does not have to be.',
    timing: '8:00am–6:00pm',
    bestFor: 'Windy + rainy mornings',
    accent: 'turq',
    stops: [
      {
        id: 'range-bernalillo',
        time: '8:00am',
        name: 'The Range Café — Bernalillo',
        kind: 'eat',
        distance: 'About 12 miles north',
        area: '87004 · Bernalillo',
        why: 'Head opposite the city traffic for a warm, colorful New Mexico breakfast and a calmer reset after a weather cancellation.',
        href: mapsLink('The Range Cafe Bernalillo NM'),
        linkLabel: 'Open in Maps',
        indoor: true,
      },
      {
        id: 'natural-history-backup',
        time: '10:00am',
        name: 'New Mexico Museum of Natural History',
        kind: 'do',
        distance: 'About 12 miles',
        area: '87104 · Museum Row',
        why: 'A fully indoor, all-ages trip through New Mexico’s dinosaurs, volcanoes, and space story.',
        href: 'https://www.nmnaturalhistory.org/visitors/visitor-information',
        linkLabel: 'Hours + admission',
        indoor: true,
        closedWeekdays: [2],
        alternate: {
          id: 'explora-weather-tuesday',
          time: '10:00am',
          name: 'Explora',
          kind: 'do',
          distance: 'About 12 miles',
          area: '87104 · Museum Row',
          why: 'The Natural History Museum is closed Tuesday, so use Explora’s 250-plus indoor, hands-on exhibits instead.',
          note: 'Open daily 10am–5pm.',
          href: 'https://www.explora.us/visitor-information/',
          linkLabel: 'Hours + tickets',
          indoor: true,
        },
      },
      {
        id: 'aquarium',
        time: '1:00pm',
        name: 'ABQ BioPark Aquarium',
        kind: 'do',
        distance: 'About 13 miles',
        area: '87104 · West Central',
        why: 'Stay inside with river otters, reefs, and sharks; aquarium admission is separate from needing good balloon weather.',
        note: 'Choose the Aquarium portion; the Botanic Garden is outdoors.',
        href: 'https://www.cabq.gov/artsculture/biopark/aquarium',
        linkLabel: 'Plan the aquarium',
        indoor: true,
      },
      {
        id: 'sandia-resort',
        time: '4:00pm',
        name: 'Sandia Resort & Casino',
        kind: 'eat',
        distance: 'About 5 miles',
        area: '87113 · North Albuquerque',
        why: 'Finish somewhere close to the Fiesta corridor with indoor dining, coffee, spa, and entertainment under one roof.',
        href: 'https://www.sandiacasino.com/dining/',
        linkLabel: 'Browse dining',
        indoor: true,
      },
    ],
  },
]

export const FIESTA_DAYS = [
  { date: '2026-10-03', short: 'Sat 3' },
  { date: '2026-10-04', short: 'Sun 4' },
  { date: '2026-10-05', short: 'Mon 5' },
  { date: '2026-10-06', short: 'Tue 6' },
  { date: '2026-10-07', short: 'Wed 7' },
  { date: '2026-10-08', short: 'Thu 8' },
  { date: '2026-10-09', short: 'Fri 9' },
  { date: '2026-10-10', short: 'Sat 10' },
  { date: '2026-10-11', short: 'Sun 11' },
]

export const NO_PARK_AND_RIDE_DATES = new Set(['2026-10-05', '2026-10-06', '2026-10-07'])
export const GLOWDEO_DATES = new Set(['2026-10-08', '2026-10-09'])
